### ISSUE TITLE
Activated Plugin and Subscription Renewals are erring out

### ISSUE THREAD

**Issue by agroot** [jrick1229/woocommerce-subscriptions-auto-complete-orders#4]
Thanks for the plugin! We're having an issue when the renewal order happens, we receive the payment, but their subscription is then placed "on-hold" and there aren't any order notes("Status changed from Pending to Active", "Payment status marked complete", etc.) on their renewal order. So it seems like the plugin is trying to complete the order too early and not allowing the renewal order to go all the way through before it marks the order status as complete. Thus erring out after we receive payment...

Currently we're using WC 3.5.4 and WCS 2.4.3

Below is the error I get in the logs:
`04-18-2019 @ 12:07:35 - scheduled action 29119 (subscription payment) failed to finish processing after 300 seconds`
`04-18-2019 @ 12:07:35 - action args: subscription_id: 28951`

Thanks

**Comment by jrick1229** [comment]
I've just updated with a new release: v3.0
I rolled back to our initial method of auto-completing, which will now definitely rely on _woocommerce_payment_complete_ being triggered.

I'm going to go ahead and close this, but let me know if you still have this issue after updating.

**Comment by synctree-mst** [comment]
Facing the same issue here .Please assist.
